### ISSUE TITLE
Unquote wpdb::prepare placeholders

### ISSUE THREAD

**Issue by j3k0** [chesio/google-sitemap-generator#1]
https://github.com/chesio/google-sitemap-generator/blob/4643f7cdfe99629d4973f22ee2b7e8895a2ee0bb/sitemap-builder.php#L132

Acording to documentation, `%s` placeholders shouldn't be quoted.

https://developer.wordpress.org/reference/classes/wpdb/prepare/

> The following placeholders can be used in the query string: %d (integer) %f (float) %s (string)
>
> All **placeholders MUST be left unquoted in the query string**. A corresponding argument MUST be passed for each placeholder.

Seems important to them.

I just so happened to have stumbled upon that.

**Comment by chesio** [comment]
Hi @j3k0,

Thanks for your time taken to report the issue!

Please note that although I've fixed this issue, this repo is just a fork of the [official plugin](https://wordpress.org/plugins/google-sitemap-generator/), so if you want to have it fixed there, you need to go to [support forums](https://wordpress.org/support/plugin/google-sitemap-generator) at WordPress.org (or contact the author via other means).
